# a more complete example of the linters which includes testing.
name: lint

on: [push, pull_request]

# the defined jobs
jobs:
  # the job build configuration and steps
  build:
    # we use ubuntu latest for this, which normally is the most recent LTS version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # using 3.7 for now only.
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python version ${{ matrix.python-version }}...
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Installing dependencies...
        # install the dependencies along with a set of required packages; if requirements is present
        # then, we install that as well.
        run: |
          python -m pip install -U pip
          pip install flake8 flake8-black pylint pre-commit
          if [ -f requirements.txt ]; then pip install -r ./requirements.txt; fi
          sudo wget https://github.com/mvdan/sh/releases/download/v3.3.0/shfmt_v3.3.0_linux_amd64 -O /bin/shfmt
          sudo chmod +x /bin/shfmt
      # Python linting phase
      - name: Running pre-commit hooks...
        uses: pre-commit/action@v2.0.0
      # Shell linting phase
      - name: Running shell check...
        uses: ludeeus/action-shellcheck@master
